### ISSUE TITLE
Which web platform to use?

### ISSUE THREAD

**Issue by schae234** [schae234/LabWebsite#2]
For a website that is easliy deployable, what platform would be best for building this on?

**Comment by EliKrumholz** [comment]
Some technologies that would be nice to integrate with a potential website:

Evernote: https://dev.evernote.com/doc/
Twitter: https://dev.twitter.com/overview/documentation
Mendeley: http://dev.mendeley.com/

**Comment by kinow** [comment]
We are using GitHub pages for BioUno, with Jekyll for building the site. You push to git, and the website is updated.

**Comment by schae234** [comment]
@kinow You suggested the one we ended up going with :+1:. Have you ever dealt with any node.js based templating engines? We are trying to keep the languages we are dealing with down to a minimum. If you were to deploy this on your own server for instance instead of relying on github to render your pages, you'd have to have ruby configured, right?

**Comment by kinow** [comment]
Hi @schae234!

> Have you ever dealt with any node.js based templating engines?

I worked on a project that used Handlebars.js, and in the past used Mustache.js and the template engine in underscore.js (in conjunction with Backbone.js). But never on a very large projects, these were all simple applications with less than 20 screens.

> We are trying to keep the languages we are dealing with down to a minimum. 

Good idea! :smile:

> If you were to deploy this on your own server for instance instead of relying on github to render your pages, you'd have to have ruby configured, right?

Not really. I had a project with Jekyll that was deployed to an Apache httpd server without Ruby. The project was built in Jenkins (which had Ruby, Jekyll, etc), where the static version was created and then uploaded via SCP to the server.

**Comment by schae234** [comment]
Thanks @kinow, so many hip JavaScript libraries so little time. We were looking at moustache, also heard of handlebar.js. I think for now, we are going to try to get things going with just github pages so that means sticking with Jekyll. Seemed like the fastest way to get something done.

You guys are in New Zealand? Sorry we couldn't meet during the Sprint...

**Comment by kinow** [comment]
Sounds like a good plan. Use Jekyll now, and move to the next issue in the list :-) 

I'm in New Zealand, Ioannis and a few others are im US or in Americas timezones, but I was the only one with time for the sprint :) Let's catch up on IRC or continue the discussions here after the sprint. I'm watching this repository, and looking forward to seeing LabWebsite go live.
